---
- hosts: webservers
  remote_user: semaphore
  become: true
  tasks:
    - name: Print OS info
      ansible.builtin.command:
        cmd: uname -a
      register: os_info

    - debug:
        var: os_info.stdout

    - name: Install Apache package
      ansible.builtin.package:
        name: "{{ 'httpd' if ansible_facts['os_family'] == 'RedHat' else 'apache2' }}"
        state: present

    - name: Ensure Apache is enabled and started
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_facts['os_family'] == 'RedHat' else 'apache2' }}"
        state: started
        enabled: true
